// Generated by CoffeeScript 1.7.1
(function() {
  App.register("{{id}}", function(params, scope, widgets) {
    var $container, load, loader, response;
    $container = scope.$id(params["containerId"]);
    response = scope.createResponse();
    loader = scope.createLoader(response);
    load = function() {
      return loader.pull(params["url"]);
    };
    response.bindLoad(function() {
      return $container.html(this.getContent());
    });
    response.bindContext(function() {
      var context;
      context = this.getContext();
      if (context && context.bindApply) {
        return context.bindApply(function() {
          response.triggerApply();
          return load();
        });
      }
    });
    load();
    return {
      bindApply: function(callback) {
        return response.bindApply(callback);
      },
      reload: function() {
        return load();
      }
    };
  });

}).call(this);

//# sourceMappingURL=loaderArea.map
